[package]
name = "sentinel-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
sha3 = "0.10"
rand = "0.8"
rand_chacha = "0.3"
serde = { workspace = true, features = ["derive"] }
