[package]
name = "sentinel-rules"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
tracing.workspace = true
sentinel-cpg = { path = "../sentinel-cpg" }
rayon = "1.8"
aho-corasick = "1.1"
serde_json = { workspace = true }
